const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Game = require('./models/Game');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '.env') });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/gamevaultx';

mongoose.connect(MONGODB_URI)
    .then(() => console.log('MongoDB Connected for Seeding'))
    .catch(err => console.error(err));

const defaultSysReq = {
    minimum: { os: "Windows 10", cpu: "i5-4460", gpu: "GTX 960", ram: "8GB", storage: "50GB" },
    recommended: { os: "Windows 11", cpu: "i7-8700", gpu: "RTX 2060", ram: "16GB", storage: "50GB" }
};

const games = [
    // --- Classic Era (2000-2004) ---
    { title: "Counter-Strike 1.6", shortDescription: "Tactical shooter legend.", description: "Terrorists vs Counter-Terrorists.", story: "Defuse the bomb or rescue hostages.", features: ["Tactical", "Multiplayer", "Mods"], genre: "FPS", developer: "Valve", publisher: "Valve", releaseYear: 2000, yearRange: "2000-2004", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/10/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/10/", price: 480 }] },
    { title: "Diablo II", shortDescription: "Definitive ARPG.", description: "Hunt Diablo.", story: "Stop the Dark Wanderer.", features: ["Loot", "Classes", "Dark Fantasy"], genre: "RPG", developer: "Blizzard", publisher: "Blizzard", releaseYear: 2000, yearRange: "2000-2004", posterImage: "https://bnetcmsus-a.akamaihd.net/cms/blog_header/2g/2G4V98D7W5O31664405626244.png", systemRequirements: defaultSysReq, providers: [{ name: "Battle.net", url: "https://diablo2.blizzard.com/", price: 999 }] },
    { title: "The Sims", shortDescription: "Life simulation.", description: "Play with life.", story: "Create and control people.", features: ["Build Mode", "Life Sim"], genre: "Simulation", developer: "Maxis", publisher: "EA", releaseYear: 2000, yearRange: "2000-2004", posterImage: "https://upload.wikimedia.org/wikipedia/en/2/23/The_Sims_Coverart.png", systemRequirements: defaultSysReq, providers: [{ name: "Official Site", url: "https://www.ea.com/", price: 499 }] },
    { title: "Age of Empires II", shortDescription: "Medieval RTS.", description: "Build an empire.", story: "Historical campaigns.", features: ["RTS", "History"], genre: "RTS", developer: "Ensemble", publisher: "Microsoft", releaseYear: 1999, yearRange: "2000-2004", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/221380/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/221380/", price: 499 }] },
    { title: "Deus Ex", shortDescription: "Cyberpunk immersive sim.", description: "Conspiracy theories real.", story: "JC Denton fights the Illuminati.", features: ["Choice", "RPG Elements"], genre: "RPG", developer: "Ion Storm", publisher: "Eidos", releaseYear: 2000, yearRange: "2000-2004", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/6910/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/6910/", price: 249 }] },
    { title: "Max Payne", shortDescription: "Bullet time noir.", description: "Hard-boiled cop revenge.", story: "Max loses his family.", features: ["Bullet Time", "Noir"], genre: "TPS", developer: "Remedy", publisher: "Rockstar", releaseYear: 2001, yearRange: "2000-2004", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/12140/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/12140/", price: 349 }] },
    { title: "Quake III Arena", shortDescription: "Arena shooter.", description: "Fast paced multiplayer.", story: "Gladiatorial combat.", features: ["Speed", "Jumping"], genre: "FPS", developer: "id Software", publisher: "Bethesda", releaseYear: 1999, yearRange: "2000-2004", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2200/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/2200/", price: 499 }] },
    { title: "Unreal Tournament", shortDescription: "GOTY Arena shooter.", description: "Kill or be killed.", story: "Tournament of the future.", features: ["Flak Cannon", "Headshots"], genre: "FPS", developer: "Epic", publisher: "Epic", releaseYear: 1999, yearRange: "2000-2004", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/13240/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/13240/", price: 399 }] },
    { title: "Warcraft III", shortDescription: "Hero RTS.", description: "Azeroth at war.", story: "Reign of Chaos.", features: ["Heroes", "Story"], genre: "RTS", developer: "Blizzard", publisher: "Blizzard", releaseYear: 2002, yearRange: "2000-2004", posterImage: "https://bnetcmsus-a.akamaihd.net/cms/blog_header/2g/2G4V98D7W5O31664405626244.png", systemRequirements: defaultSysReq, providers: [{ name: "Battle.net", url: "https://warcraft3.blizzard.com/", price: 2999 }] },
    { title: "Command & Conquer: Red Alert 2", shortDescription: "Soviet invasion.", description: "RTS classic.", story: "Time travel war.", features: ["Kirovs", "Tesla"], genre: "RTS", developer: "Westwood", publisher: "EA", releaseYear: 2000, yearRange: "2000-2004", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2229850/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/2229850/", price: 499 }] },

    // --- Golden Age (2005-2009) ---
    { title: "Half-Life 2", shortDescription: "Physics FPS.", description: "Freeman returns.", story: "City 17 uprising.", features: ["Gravity Gun", "Physics"], genre: "FPS", developer: "Valve", publisher: "Valve", releaseYear: 2004, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/220/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/220/", price: 480 }] },
    { title: "World of Warcraft", shortDescription: "The MMORPG.", description: "Azeroth online.", story: "Alliance vs Horde.", features: ["Raids", "Quests"], genre: "MMORPG", developer: "Blizzard", publisher: "Blizzard", releaseYear: 2004, yearRange: "2005-2009", posterImage: "https://bnetcmsus-a.akamaihd.net/cms/blog_header/2g/2G4V98D7W5O31664405626244.png", systemRequirements: defaultSysReq, providers: [{ name: "Battle.net", url: "https://worldofwarcraft.blizzard.com/", price: 1299 }] },
    { title: "GTA: San Andreas", shortDescription: "Gangsta life.", description: "CJ in Los Santos.", story: "Grove Street.", features: ["Open World", "Stats"], genre: "Action", developer: "Rockstar", publisher: "Rockstar", releaseYear: 2004, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1547000/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1547000/", price: 499 }] },
    { title: "NFS: Most Wanted", shortDescription: "Street racing.", description: "Outrun cops.", story: "Blacklist 15.", features: ["Pursuits", "Tuning"], genre: "Racing", developer: "EA Black Box", publisher: "EA", releaseYear: 2005, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1262560/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1262560/", price: 999 }] },
    { title: "Crysis", shortDescription: "Can it run Crysis?", description: "High tech suit.", story: "Aliens on island.", features: ["Nanosuit", "Graphics"], genre: "FPS", developer: "Crytek", publisher: "EA", releaseYear: 2007, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/17300/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/17300/", price: 999 }] },
    { title: "CoD 4: Modern Warfare", shortDescription: "Modern FPS defined.", description: "Cinema warfare.", story: "Nuclear threat.", features: ["Multiplayer", "Campaign"], genre: "FPS", developer: "Infinity Ward", publisher: "Activision", releaseYear: 2007, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/7940/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/7940/", price: 999 }] },
    { title: "Portal", shortDescription: "Thinking with portals.", description: "Puzzle platformer.", story: "Cake is a lie.", features: ["Portals", "GLaDOS"], genre: "Puzzle", developer: "Valve", publisher: "Valve", releaseYear: 2007, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/400/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/400/", price: 480 }] },
    { title: "Company of Heroes", shortDescription: "WW2 RTS.", description: "Tactical warfare.", story: "Normandy invasion.", features: ["Cover", "Destruction"], genre: "RTS", developer: "Relic", publisher: "SEGA", releaseYear: 2006, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/228200/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/228200/", price: 899 }] },
    { title: "BioShock", shortDescription: "Underwater dystopia.", description: "Rapture awaits.", story: "Would you kindly.", features: ["Plasmids", "Atmosphere"], genre: "FPS", developer: "Irrational", publisher: "2K", releaseYear: 2007, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/7670/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/7670/", price: 899 }] },
    { title: "Left 4 Dead", shortDescription: "Zombie co-op.", description: "Fight the horde.", story: "Escape to safety.", features: ["Director AI", "Co-op"], genre: "FPS", developer: "Valve", publisher: "Valve", releaseYear: 2008, yearRange: "2005-2009", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/500/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/500/", price: 480 }] },

    // --- HD Era (2010-2014) ---
    { title: "Minecraft", shortDescription: "Build anything.", description: "Blocks and craft.", story: "Survival.", features: ["Creative", "Redstone"], genre: "Sandbox", developer: "Mojang", publisher: "Xbox", releaseYear: 2011, yearRange: "2010-2014", posterImage: "https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png", systemRequirements: defaultSysReq, providers: [{ name: "Official Site", url: "https://minecraft.net", price: 1999 }] },
    { title: "Mass Effect 2", shortDescription: "Suicide mission.", description: "Save galaxy.", story: "Collectors threat.", features: ["Loyalty", "Characters"], genre: "RPG", developer: "BioWare", publisher: "EA", releaseYear: 2010, yearRange: "2010-2014", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1328670/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1328670/", price: 2999 }] },
    { title: "StarCraft II", shortDescription: "Ultimate RTS.", description: "Terran campaign.", story: "Jim Raynor.", features: ["Esports", "Cinematics"], genre: "RTS", developer: "Blizzard", publisher: "Blizzard", releaseYear: 2010, yearRange: "2010-2014", posterImage: "https://bnetcmsus-a.akamaihd.net/cms/blog_header/2g/2G4V98D7W5O31664405626244.png", systemRequirements: defaultSysReq, providers: [{ name: "Battle.net", url: "https://starcraft2.com", price: 0 }] },
    { title: "Battlefield 3", shortDescription: "Modern warfare chaos.", description: "Large scale battles.", story: "War on terror.", features: ["Destruction", "Jets"], genre: "FPS", developer: "DICE", publisher: "EA", releaseYear: 2011, yearRange: "2010-2014", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1238860/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1238860/", price: 2499 }] },
    { title: "Skyrim", shortDescription: "Dragonborn.", description: "Open world fantasy.", story: "Alduin returns.", features: ["Shouts", "Mods"], genre: "RPG", developer: "Bethesda", publisher: "Bethesda", releaseYear: 2011, yearRange: "2010-2014", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/489830/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/489830/", price: 1799 }] },
    { title: "Dark Souls", shortDescription: "Prepare to Die.", description: "Hardcore ARPG.", story: "Link the fire.", features: ["Difficulty", "Bosses"], genre: "ARPG", developer: "FromSoftware", publisher: "Bandai", releaseYear: 2011, yearRange: "2010-2014", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570940/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/570940/", price: 2499 }] },
    { title: "Far Cry 3", shortDescription: "Insanity.", description: "Tropical island.", story: "Vaas Montenegro.", features: ["Open World", "Stealth"], genre: "FPS", developer: "Ubisoft", publisher: "Ubisoft", releaseYear: 2012, yearRange: "2010-2014", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/220240/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/220240/", price: 1499 }] },
    { title: "Dota 2", shortDescription: "The MOBA.", description: "5v5 battle.", story: "Dire vs Radiant.", features: ["Depth", "Heroes"], genre: "MOBA", developer: "Valve", publisher: "Valve", releaseYear: 2013, yearRange: "2010-2014", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/570/", price: 0 }] },
    { title: "Assassin's Creed IV", shortDescription: "Pirate life.", description: "Caribbean seas.", story: "Edward Kenway.", features: ["Naval Combat", "Pirates"], genre: "Action", developer: "Ubisoft", publisher: "Ubisoft", releaseYear: 2013, yearRange: "2010-2014", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/242050/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/242050/", price: 1999 }] },
    { title: "Watch Dogs", shortDescription: "Hacking city.", description: "Chicago OS.", story: "Aiden Pearce.", features: ["Hacking", "Stealth"], genre: "Action", developer: "Ubisoft", publisher: "Ubisoft", releaseYear: 2014, yearRange: "2010-2014", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/243470/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/243470/", price: 1499 }] },

    // --- Modern Era (2015-2019) ---
    { title: "The Witcher 3", shortDescription: "Masterpiece RPG.", description: "Geralt's journey.", story: "Find Ciri.", features: ["Story", "World"], genre: "RPG", developer: "CDPR", publisher: "CDPR", releaseYear: 2015, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/292030/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/292030/", price: 899 }] },
    { title: "GTA V", shortDescription: "Ultimate open world.", description: "Heists in LA.", story: "Three criminals.", features: ["Heists", "Online"], genre: "Action", developer: "Rockstar", publisher: "Rockstar", releaseYear: 2015, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/271590/", price: 2321 }] },
    { title: "Fallout 4", shortDescription: "Post-apocalyptic.", description: "Boston ruins.", story: "Find son.", features: ["Building", "Crafting"], genre: "RPG", developer: "Bethesda", publisher: "Bethesda", releaseYear: 2015, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/377160/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/377160/", price: 1599 }] },
    { title: "DOOM (2016)", shortDescription: "Rip and tear.", description: "Fast FPS.", story: "Mars demons.", features: ["Glory Kills", "Speed"], genre: "FPS", developer: "id", publisher: "Bethesda", releaseYear: 2016, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/379720/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/379720/", price: 1199 }] },
    { title: "Overwatch", shortDescription: "Hero shooter.", description: "Team combat.", story: "Heroes unite.", features: ["Heroes", "Roles"], genre: "FPS", developer: "Blizzard", publisher: "Blizzard", releaseYear: 2016, yearRange: "2015-2019", posterImage: "https://bnetcmsus-a.akamaihd.net/cms/blog_header/2g/2G4V98D7W5O31664405626244.png", systemRequirements: defaultSysReq, providers: [{ name: "Battle.net", url: "https://overwatch.blizzard.com", price: 0 }] },
    { title: "PUBG", shortDescription: "Battle Royale.", description: "100 players.", story: "Survivors.", features: ["Loot", "Survive"], genre: "BR", developer: "Krafton", publisher: "Krafton", releaseYear: 2017, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/578080/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/578080/", price: 999 }] },
    { title: "Rainbow Six Siege", shortDescription: "Tactical breach.", description: "Destructible environment.", story: "CTU ops.", features: ["Destruction", "Operators"], genre: "FPS", developer: "Ubisoft", publisher: "Ubisoft", releaseYear: 2015, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/359550/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/359550/", price: 999 }] },
    { title: "Forza Horizon 4", shortDescription: "Racing seasons.", description: "UK festival.", story: "Become superstar.", features: ["Seasons", "Cars"], genre: "Racing", developer: "Playground", publisher: "Microsoft", releaseYear: 2018, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1293830/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1293830/", price: 1299 }] },
    { title: "Sekiro", shortDescription: "Shinobi action.", description: "Parry master.", story: "Protect lord.", features: ["Combat", "Posture"], genre: "Action", developer: "FromSoftware", publisher: "Activision", releaseYear: 2019, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/814380/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/814380/", price: 3999 }] },
    { title: "Red Dead Redemption 2", shortDescription: "Western epic.", description: "Arthur Morgan.", story: "Gang tragedy.", features: ["Detail", "World"], genre: "Action", developer: "Rockstar", publisher: "Rockstar", releaseYear: 2019, yearRange: "2015-2019", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1174180/", price: 3199 }] },

    // --- Next-Gen (2020-2022) ---
    { title: "Cyberpunk 2077", shortDescription: "Night City.", description: "Tech noir.", story: "Immortality chip.", features: ["Cyberware", "Choices"], genre: "RPG", developer: "CDPR", publisher: "CDPR", releaseYear: 2020, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1091500/", price: 2999 }] },
    { title: "Valorant", shortDescription: "5v5 Shooter.", description: "Tactical abilities.", story: "Agents.", features: ["Precise", "Abilities"], genre: "FPS", developer: "Riot", publisher: "Riot", releaseYear: 2020, yearRange: "2020-2022", posterImage: "https://img.redbull.com/images/c_limit,w_1500,h_1000,f_auto,q_auto/redbullcom/2020/6/5/ctk2ivthlh4799000000/valorant-art", systemRequirements: defaultSysReq, providers: [{ name: "Riot", url: "https://playvalorant.com", price: 0 }] },
    { title: "MS Flight Simulator", shortDescription: "Fly anywhere.", description: "Real earth.", story: "Pilot career.", features: ["Realism", "Cloud"], genre: "Sim", developer: "Asobo", publisher: "Microsoft", releaseYear: 2020, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1250410/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1250410/", price: 3999 }] },
    { title: "AC Valhalla", shortDescription: "Viking saga.", description: "Raid England.", story: "Eivor.", features: ["Raids", "Settlement"], genre: "RPG", developer: "Ubisoft", publisher: "Ubisoft", releaseYear: 2020, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2208920/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/2208920/", price: 2999 }] },
    { title: "Horizon Zero Dawn", shortDescription: "Robot dinos.", description: "Aloy's origins.", story: "Post-post-apoc.", features: ["Bow", "Machines"], genre: "Action", developer: "Guerrilla", publisher: "PlayStation", releaseYear: 2020, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1151640/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1151640/", price: 3299 }] },
    { title: "Resident Evil Village", shortDescription: "Gothic horror.", description: "Ethan Winters.", story: "Save Rose.", features: ["Vampires", "Werewolves"], genre: "Horror", developer: "Capcom", publisher: "Capcom", releaseYear: 2021, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1196590/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1196590/", price: 2999 }] },
    { title: "Forza Horizon 5", shortDescription: "Mexico racing.", description: "Open road.", story: "Horizon festival.", features: ["Visuals", "Scale"], genre: "Racing", developer: "Playground", publisher: "Microsoft", releaseYear: 2021, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1551360/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1551360/", price: 3499 }] },
    { title: "God of War", shortDescription: "Boy.", description: "Norse realms.", story: "Father and son.", features: ["Axe", "Story"], genre: "Action", developer: "Santa Monica", publisher: "PlayStation", releaseYear: 2022, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1593500/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1593500/", price: 3299 }] },
    { title: "Dying Light 2", shortDescription: "Parkour zombies.", description: "City decay.", story: "Choices matter.", features: ["Parkour", "Combat"], genre: "Action", developer: "Techland", publisher: "Techland", releaseYear: 2022, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/534380/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/534380/", price: 2999 }] },
    { title: "CoD: Modern Warfare II", shortDescription: "Task Force 141.", description: "Global threat.", story: "Operations.", features: ["Gunplay", "Warzone"], genre: "FPS", developer: "Infinity Ward", publisher: "Activision", releaseYear: 2022, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1938090/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1938090/", price: 4999 }] },
    { title: "Elden Ring", shortDescription: "GOTY.", description: "Lands Between.", story: "Marika's offspring.", features: ["Open World", "Builds"], genre: "RPG", developer: "FromSoftware", publisher: "Bandai", releaseYear: 2022, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1245620/", price: 3599 }] },

    // --- New Era (2023-Present) ---
    { title: "God of War Ragnarök", shortDescription: "Fimbulwinter is underway.", description: "Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle that will end the world.", story: "The saga continues.", features: ["Leviathan Axe", "Blades of Chaos", "Nine Realms"], genre: "Action", developer: "Santa Monica", publisher: "PlayStation", releaseYear: 2024, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2322010/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/2322010/", price: 3999 }] },
    { title: "Senua's Saga: Hellblade II", shortDescription: "Cinematic immersion.", description: "Intent on saving those who have fallen victim to the horrors of tyranny, Senua battles to overcome the darkness within and without.", story: "A journey of mental health and myth.", features: ["UE5 Graphics", "Binaural Audio"], genre: "Action", developer: "Ninja Theory", publisher: "Xbox", releaseYear: 2024, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2461850/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/2461850/", price: 3599 }] },
    { title: "A Plague Tale: Requiem", shortDescription: "Heartrending journey.", description: "Amicia and Hugo travel far south, to new regions and vibrant cities. But when Hugo's powers reawaken, death returned.", story: "The Macula curse.", features: ["Stealth", "Rats"], genre: "Adventure", developer: "Asobo", publisher: "Focus", releaseYear: 2022, yearRange: "2020-2022", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1182900/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1182900/", price: 1999 }] },
    { title: "Baldur's Gate 3", shortDescription: "RPG perfection.", description: "D&D epic.", story: "Mind flayers.", features: ["Decisions", "Freedom"], genre: "RPG", developer: "Larian", publisher: "Larian", releaseYear: 2023, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1086940/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1086940/", price: 2999 }] },
    { title: "Starfield", shortDescription: "NASA punk.", description: "Space exploration.", story: "Constellation.", features: ["Ship building", "Planets"], genre: "RPG", developer: "Bethesda", publisher: "Bethesda", releaseYear: 2023, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1716740/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1716740/", price: 4999 }] },
    { title: "Alan Wake 2", shortDescription: "Spiral horror.", description: "Dark Place.", story: "Write reality.", features: ["Meta", "Horror"], genre: "Horror", developer: "Remedy", publisher: "Epic", releaseYear: 2023, yearRange: "2023-Present", posterImage: "https://image.api.playstation.com/vulcan/ap/rnd/202305/2420/8617f692796e62241cf4dc8c90382020e5088c4a96162358.png", systemRequirements: defaultSysReq, providers: [{ name: "Epic", url: "https://store.epicgames.com", price: 3199 }] },
    { title: "Lies of P", shortDescription: "Pinocchio Souls.", description: "Steampunk city.", story: "Geppetto's puppet.", features: ["Weapon arms", "Lying"], genre: "Souls", developer: "Neowiz", publisher: "Neowiz", releaseYear: 2023, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1627720/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1627720/", price: 3499 }] },
    { title: "Palworld", shortDescription: "Pokemon with guns.", description: "Survival crafting.", story: "Catch Pals.", features: ["Pals", "Automation"], genre: "Survival", developer: "Pocketpair", publisher: "Pocketpair", releaseYear: 2024, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1623730/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1623730/", price: 1300 }] },
    { title: "Black Myth: Wukong", shortDescription: "Monkey King.", description: "Chinese myth.", story: "Journey West.", features: ["Combat", "UE5"], genre: "Action", developer: "Game Science", publisher: "Game Science", releaseYear: 2024, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2358720/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/2358720/", price: 3599 }] },
    { title: "Hades II", shortDescription: "Daughter of Hades.", description: "Roguelike sequel.", story: "Kill Time.", features: ["Witchcraft", "Gods"], genre: "Roguelike", developer: "Supergiant", publisher: "Supergiant", releaseYear: 2024, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145350/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1145350/", price: 1100 }] },
    { title: "Dragon's Dogma 2", shortDescription: "Arisen returns.", description: "Fantasy sim.", story: "Dragon cycle.", features: ["Physics", "Pawns"], genre: "RPG", developer: "Capcom", publisher: "Capcom", releaseYear: 2024, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2054970/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/2054970/", price: 4499 }] },
    { title: "S.T.A.L.K.E.R. 2", shortDescription: "Zone awaits.", description: "Chornobyl horror.", story: "Artifact hunt.", features: ["Atmosphere", "Survival"], genre: "FPS", developer: "GSC", publisher: "GSC", releaseYear: 2024, yearRange: "2023-Present", posterImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1643320/library_hero.jpg", systemRequirements: defaultSysReq, providers: [{ name: "Steam", url: "https://store.steampowered.com/app/1643320/", price: 3999 }] }
];

const seedDB = async () => {
    try {
        await Game.deleteMany({});
        await Game.insertMany(games);
        console.log(`Database Seeded with ${games.length} games!`);
    } catch (err) {
        console.error('Seeding Error:', err);
    } finally {
        mongoose.connection.close();
    }
};

seedDB();